apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: istio-discovery
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: istio-discovery
    chartVersion: 1.2.0

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    global:
      istioNamespace: '{{repl Namespace }}'

  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder: {}
