apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: istio-operator
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: istio-operator
    chartVersion: 1.7.0

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    operatorNamespace: '{{repl Namespace }}'
    watchedNamespaces: '{{repl ConfigOption "istio_namespace" }}'

  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder: {}
